# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dbfea147fe38ed0966e945bd0ee8320861974c4e08ead99132f65dd1818cec5c572cd8ba2c3af474e6b0d9ef2d40f9877a6aa48d8f27d7cc9c443d68739335cb

test:
  secret_key_base: c1bbd1fb845a1818194f8604c0deccc454e7f406f1fa0a1d843a1a6c5dfe4037a05a9afad9203ae2c4bd1d013c3712bd2a6efe174dad77c58cfa751e8f65deea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
